#!/usr/bin/env python3
"""Distill the ORC certificate export (boatspeed_gospel.md) into clean artifacts.

The raw export (data.orc.org Speed Guide for SR33 "C4", CAN100) contains, among the
polar-curve graphics, machine-readable "Best Performance" tables — one per TWS — with
columns TWA, BTV (target boatspeed), VMG, AWS, AWA, Heel, Reef, Flat. This script extracts
the Best Performance envelope (the optimal sail-selection polar) and emits:

  1. sr33_speed_guide.md  — a clean reference loaded into the agent's standing context.
  2. ../../db/seed/polars_sr33.sql — real polar data (target_stw=BTV, target_vmg=VMG) to
     replace the synthetic placeholder polars in the DB.

Re-run if the ORC certificate is updated:  python3 vps/agent/knowledge/build_speed_guide.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "boatspeed_gospel.md")
GUIDE = os.path.join(HERE, "sr33_speed_guide.md")
SEED = os.path.abspath(os.path.join(HERE, "..", "..", "db", "seed", "polars_sr33.sql"))

NUM = lambda s: float(s.replace("°", "").strip())


def parse_best_performance(text):
    lines = text.splitlines()
    start = next(i for i, l in enumerate(lines) if "**Best Performance**" in l)
    blocks = {}          # tws -> list of row dicts
    tws = None
    for l in lines[start:]:
        s = l.strip()
        if "Headsail," in s:               # next group begins — stop
            break
        m = re.match(r"TWS = (\d+)kts", s)
        if m:
            tws = int(m.group(1))
            blocks[tws] = []
            continue
        if tws is not None and s.startswith("|"):
            cells = [c.strip() for c in s.strip("|").split("|")]
            if len(cells) == 8 and re.match(r"^[\d.]+°?$", cells[0]):
                twa, btv, vmg, aws, awa, heel, reef, flat = cells
                blocks[tws].append({
                    "twa": NUM(twa), "btv": NUM(btv), "vmg": NUM(vmg),
                    "aws": NUM(aws), "awa": NUM(awa), "heel": NUM(heel),
                    "reef": NUM(reef), "flat": NUM(flat),
                })
    return blocks


def write_guide(blocks):
    out = []
    out.append("# SR33 \"C4\" — ORC Speed Guide (Best Performance polar)\n")
    out.append("Boat: SR33 *C4*, sail #CAN100 (ORC ref 03430004T3F). Source of truth for "
               "target boat speed. **BTV** = target boatspeed through water (kn); **VMG** = "
               "velocity made good (kn); **AWS/AWA** = expected apparent wind at the target; "
               "**Heel** = target heel (°); **Reef/Flat** = sail depowering factors "
               "(1.00 = full power; <1.00 = reef/flatten). Per true wind speed (TWS).\n")
    for tws in sorted(blocks):
        rows = blocks[tws]
        if not rows:
            continue
        # Highlight upwind & downwind optimum VMG angles.
        up = max((r for r in rows if r["twa"] <= 90), key=lambda r: r["vmg"], default=None)
        dn = max((r for r in rows if r["twa"] > 90), key=lambda r: r["vmg"], default=None)
        out.append(f"\n## TWS {tws} kn")
        if up and dn:
            out.append(f"*Optimum beat: TWA {up['twa']:.1f}° → {up['btv']:.2f} kn "
                       f"(VMG {up['vmg']:.2f}). Optimum run: TWA {dn['twa']:.1f}° → "
                       f"{dn['btv']:.2f} kn (VMG {dn['vmg']:.2f}).*")
        out.append("\n| TWA | BTV | VMG | AWS | AWA | Heel | Reef | Flat |")
        out.append("|----:|----:|----:|----:|----:|-----:|-----:|-----:|")
        for r in rows:
            out.append(f"| {r['twa']:.1f}° | {r['btv']:.2f} | {r['vmg']:.2f} | "
                       f"{r['aws']:.2f} | {r['awa']:.1f}° | {r['heel']:.1f}° | "
                       f"{r['reef']:.2f} | {r['flat']:.2f} |")
    open(GUIDE, "w").write("\n".join(out) + "\n")
    return GUIDE


def write_seed(blocks):
    out = ["-- SR33 \"C4\" real ORC polar (Best Performance envelope). Generated by",
           "-- vps/agent/knowledge/build_speed_guide.py from the ORC certificate.",
           "-- Replaces synthetic placeholder polars. Idempotent.",
           "DELETE FROM polars WHERE boat_id = 'sr33';"]
    vals = []
    for tws in sorted(blocks):
        for r in blocks[tws]:
            vals.append(f"  ('sr33', {tws}, {r['twa']:.1f}, {r['btv']:.2f}, {r['vmg']:.2f})")
    out.append("INSERT INTO polars (boat_id, tws, twa, target_stw, target_vmg) VALUES")
    out.append(",\n".join(vals))
    out.append("ON CONFLICT (boat_id, tws, twa) DO UPDATE")
    out.append("  SET target_stw = EXCLUDED.target_stw, target_vmg = EXCLUDED.target_vmg;")
    open(SEED, "w").write("\n".join(out) + "\n")
    return SEED


if __name__ == "__main__":
    text = open(SRC).read()
    blocks = parse_best_performance(text)
    n = sum(len(v) for v in blocks.values())
    print(f"parsed Best Performance: {len(blocks)} TWS tables, {n} polar points")
    print("wrote", write_guide(blocks))
    print("wrote", write_seed(blocks))
