"""SR33 polars for the Lab optimizer.

Parses the one canonical ORC polar file (`polars_sr33.sql`, generated by build_speed_guide.py) into
[(tws, twa, target_stw)] — the same source the onboard engine reads, so the Lab optimizes on the
same boat speeds the boat sails to. (Lab-3 will swap in REFINED polars from the learning loop; this
loader is the seam where that happens.)
"""
import json
import os
import re

POLARS_FILE = os.environ.get("POLARS_FILE", "/srv/polars_sr33.sql")
SAIL_POLARS_FILE = os.environ.get("SAIL_POLARS_FILE", "/srv/sr33_sail_polars.json")

_POLAR_RE = re.compile(
    r"\(\s*'[^']*'\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*"
    r"([0-9.]+|NULL)\s*\)"
)

_CACHE = None
_SAIL_CACHE = None


def sail_polars():
    """Per-sail polar curves `{sail_short: [(tws, twa, stw)]}` (routing fidelity 2g — sail-aware
    routing). The envelope `polars_stw()` is the max-over-sails speed; THIS is the speed of EACH
    sail across its rated TWA domain, so the optimizer can model the cost of HOLDING a sub-optimal
    sail vs PEELING. Empty dict if the file is absent — the optimizer then routes on the envelope
    only (sail-aware off), unchanged. Same generator/source as the envelope + crossovers."""
    global _SAIL_CACHE
    if _SAIL_CACHE is None:
        try:
            with open(SAIL_POLARS_FILE) as f:
                raw = json.load(f).get("sails", {})
            _SAIL_CACHE = {s: [(float(t), float(a), float(v)) for t, a, v in pts if v is not None]
                           for s, pts in raw.items()}
        except (OSError, ValueError):
            _SAIL_CACHE = {}
    return _SAIL_CACHE


def polars_stw():
    """[(tws, twa, target_stw)] from the polar SQL, parsed once."""
    global _CACHE
    if _CACHE is None:
        try:
            with open(POLARS_FILE) as f:
                text = f.read()
        except OSError:
            _CACHE = []
            return _CACHE
        _CACHE = [(float(tws), float(twa), float(stw))
                  for tws, twa, stw, _vmg in _POLAR_RE.findall(text)]
    return _CACHE
