"""SR33 polars for the Lab optimizer.

Parses the one canonical ORC polar file (`polars_sr33.sql`, generated by build_speed_guide.py) into
[(tws, twa, target_stw)] — the same source the onboard engine reads, so the Lab optimizes on the
same boat speeds the boat sails to. (Lab-3 will swap in REFINED polars from the learning loop; this
loader is the seam where that happens.)
"""
import json
import os
import re

POLARS_FILE = os.environ.get("POLARS_FILE", "/srv/polars_sr33.sql")
SAIL_POLARS_FILE = os.environ.get("SAIL_POLARS_FILE", "/srv/sr33_sail_polars.json")

_POLAR_RE = re.compile(
    r"\(\s*'[^']*'\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*"
    r"([0-9.]+|NULL)\s*\)"
)

_CACHE = None
_SAIL_CACHE = None


def sail_polars():
    """Per-sail polar curves `{sail_short: [(tws, twa, stw)]}` (routing fidelity 2g — sail-aware
    routing). The envelope `polars_stw()` is the max-over-sails speed; THIS is the speed of EACH
    sail across its rated TWA domain, so the optimizer can model the cost of HOLDING a sub-optimal
    sail vs PEELING. Empty dict if the file is absent — the optimizer then routes on the envelope
    only (sail-aware off), unchanged. Same generator/source as the envelope + crossovers."""
    global _SAIL_CACHE
    if _SAIL_CACHE is None:
        try:
            with open(SAIL_POLARS_FILE) as f:
                raw = json.load(f).get("sails", {})
            _SAIL_CACHE = {s: [(float(t), float(a), float(v)) for t, a, v in pts if v is not None]
                           for s, pts in raw.items()}
        except (OSError, ValueError):
            _SAIL_CACHE = {}
    return _SAIL_CACHE


def apply_adjustments(P, adjustments):
    """Apply the Lab-4 human-APPROVED refined-polar overlay to a polar table `P` = [(tws,twa,stw)].

    `adjustments` = [{tws, twa, mult}] — a multiplicative tweak per ORC grid cell (the cert stays the
    canonical source; this is the explicit, reviewed overlay the learning loop produces). Returns a NEW
    list (P is the module cache — never mutate it). Multipliers are clamped to a sane band so an
    approved tweak can't wildly distort the polar. Empty/none → P unchanged."""
    if not adjustments or not P:
        return P
    key = lambda tws, twa: (round(float(tws), 1), round(float(twa), 1))
    mults = {}
    for a in adjustments:
        try:
            m = float(a.get("mult"))
        except (TypeError, ValueError):
            continue
        mults[key(a.get("tws"), a.get("twa"))] = max(0.80, min(1.15, m))
    if not mults:
        return P
    return [(tws, twa, stw * mults.get(key(tws, twa), 1.0)) for (tws, twa, stw) in P]


def polars_stw():
    """[(tws, twa, target_stw)] from the polar SQL, parsed once."""
    global _CACHE
    if _CACHE is None:
        try:
            with open(POLARS_FILE) as f:
                text = f.read()
        except OSError:
            _CACHE = []
            return _CACHE
        _CACHE = [(float(tws), float(twa), float(stw))
                  for tws, twa, stw, _vmg in _POLAR_RE.findall(text)]
    return _CACHE
