"""SR33 polars for the Lab optimizer.

Parses the one canonical ORC polar file (`polars_sr33.sql`, generated by build_speed_guide.py) into
[(tws, twa, target_stw)] — the same source the onboard engine reads, so the Lab optimizes on the
same boat speeds the boat sails to. (Lab-3 will swap in REFINED polars from the learning loop; this
loader is the seam where that happens.)
"""
import os
import re

POLARS_FILE = os.environ.get("POLARS_FILE", "/srv/polars_sr33.sql")

_POLAR_RE = re.compile(
    r"\(\s*'[^']*'\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*"
    r"([0-9.]+|NULL)\s*\)"
)

_CACHE = None


def polars_stw():
    """[(tws, twa, target_stw)] from the polar SQL, parsed once."""
    global _CACHE
    if _CACHE is None:
        try:
            with open(POLARS_FILE) as f:
                text = f.read()
        except OSError:
            _CACHE = []
            return _CACHE
        _CACHE = [(float(tws), float(twa), float(stw))
                  for tws, twa, stw, _vmg in _POLAR_RE.findall(text)]
    return _CACHE
