-- DEV-ONLY placeholder metadata so the agent's tools return something in Phase 0.
-- NOT loaded in prod (prod gets real polars/waypoints via the §9 open items).
-- Safe to re-run: upserts / time-relative AIS rows.

-- Polars are now REAL ORC data — loaded separately from polars_sr33.sql (generated by
-- vps/agent/knowledge/build_speed_guide.py from the SR33 "C4" ORC certificate). See
-- seed_dev.sh, which loads it after this file.

-- Port Huron -> Mackinac-ish placeholder course (coords approximate, dev only).
DELETE FROM waypoints WHERE route = 'default';
INSERT INTO waypoints (route, seq, name, lat, lon) VALUES
  ('default', 1, 'Start (Port Huron)',   43.000, -82.420),
  ('default', 2, 'Cove Island',          45.300, -81.730),
  ('default', 3, 'Finish (Mackinac)',    45.847, -84.618);

-- A couple of recent AIS targets so get_ais_targets() is non-empty.
INSERT INTO ais_targets (time, boat_id, mmsi, name, lat, lon, sog, cog, range_nm, bearing, cpa_nm, tcpa_min) VALUES
  (now() - interval '20 seconds', 'sr33', 366123456, 'GORDON C', 43.05, -82.40, 11.2, 200, 3.1, 015, 0.4, 12.5),
  (now() - interval '25 seconds', 'sr33', 316987654, 'CSL NIAGARA', 43.12, -82.30, 13.8, 185, 7.8, 040, 2.2, 28.0);
